export const CAPABILITIES = [
  {
    id: 'makeup-tutor',
    title: '妆教',
    description: '图片和视频帧只在浏览器本地分析，逐步完成妆容教学。',
    status: 'available',
    href: '/makeup/',
    icon: 'sparkles',
    tone: 'apricot',
    privacyNote: '浏览器本地分析',
  },
  {
    id: 'virtual-fitting-room',
    title: '虚拟试衣间',
    description: '在这台设备上选照片、挑单品；穿搭预览等生图能力接入后生成。',
    status: 'available',
    href: '/tools/virtual-fitting',
    icon: 'shirt',
    tone: 'mist',
    privacyNote: '照片不出浏览器 · 生图接入中',
  },
  {
    id: 'virtual-makeup-room',
    title: '虚拟化妆间',
    description: '在这台设备上选照片、挑妆容；妆效预览等生图能力接入后生成。',
    status: 'available',
    href: '/tools/virtual-makeup',
    icon: 'wand',
    tone: 'blush',
    privacyNote: '照片不出浏览器 · 生图接入中',
  },
  {
    id: 'beauty-camera',
    title: '美颜相机',
    description: '拍照或选照片，在这台设备上实时磨皮、美白、瘦脸、大眼。',
    status: 'available',
    href: '/tools/beauty-camera',
    icon: 'camera',
    tone: 'sprout',
    privacyNote: '全在本机处理',
  },
]
