export const CAPABILITIES = [
  {
    id: 'virtual-fitting-room',
    title: '虚拟试衣间',
    description: '在这台设备上选照片、挑单品，由本机 ComfyUI 生成穿搭预览。',
    status: 'available',
    href: '/tools/virtual-fitting',
    icon: 'shirt',
    tone: 'mist',
    privacyNote: '照片只在本机处理（本地 ComfyUI 生图），不出这台设备',
  },
  {
    id: 'virtual-makeup-room',
    title: '虚拟化妆间',
    description: '在这台设备上选照片、挑妆容，由本机 ComfyUI 生成妆效预览。',
    status: 'available',
    href: '/tools/virtual-makeup',
    icon: 'wand',
    tone: 'blush',
    privacyNote: '照片只在本机处理（本地 ComfyUI 生图），不出这台设备',
  },
  {
    id: 'beauty-camera',
    title: '美颜相机',
    description: '拍照或选照片，在这台设备上实时磨皮、美白、瘦脸、大眼。',
    status: 'available',
    href: '/tools/beauty-camera',
    icon: 'camera',
    tone: 'sprout',
    privacyNote: '全在本机处理',
  },
]
